"""empty message

Revision ID: 05eaf93ba179
Revises: 63dc78740993
Create Date: 2017-04-26 16:27:45.962276

"""

# revision identifiers, used by Alembic.
revision = '05eaf93ba179'
down_revision = '63dc78740993'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluate', sa.Column('revision_id', sa.Integer(), nullable=True))
    op.drop_column('evaluate', 'created_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluate', sa.Column('created_user', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('evaluate', 'revision_id')
    # ### end Alembic commands ###
