"""empty message

Revision ID: 124fa42a7132
Revises: be94fa8f9e1d
Create Date: 2017-04-18 17:43:38.762338

"""

# revision identifiers, used by Alembic.
revision = '124fa42a7132'
down_revision = 'be94fa8f9e1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison', sa.Column('article1_chosen', sa.Integer(), nullable=True))
    op.add_column('comparison', sa.Column('article2_chosen', sa.Integer(), nullable=True))
    op.drop_column('comparison', 'article2')
    op.drop_column('comparison', 'article1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison', sa.Column('article1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comparison', sa.Column('article2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('comparison', 'article2_chosen')
    op.drop_column('comparison', 'article1_chosen')
    # ### end Alembic commands ###
