"""empty message

Revision ID: 151cca14453e
Revises: d04a505491ec
Create Date: 2017-04-18 11:26:07.784614

"""

# revision identifiers, used by Alembic.
revision = '151cca14453e'
down_revision = 'd04a505491ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revision', sa.Column('feedback_order', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revision', 'feedback_order')
    # ### end Alembic commands ###
