"""empty message

Revision ID: 3a3656c5d37a
Revises: 877a627d0db2
Create Date: 2017-04-17 22:07:33.200525

"""

# revision identifiers, used by Alembic.
revision = '3a3656c5d37a'
down_revision = '877a627d0db2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revision', sa.Column('time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revision', 'time')
    # ### end Alembic commands ###
