"""empty message

Revision ID: 6bb5ecea04e2
Revises: fab49039e1fb
Create Date: 2017-04-18 17:41:36.096825

"""

# revision identifiers, used by Alembic.
revision = '6bb5ecea04e2'
down_revision = 'fab49039e1fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison', sa.Column('article1', sa.Integer(), nullable=True))
    op.add_column('comparison', sa.Column('pair_id', sa.Text(), nullable=True))
    op.drop_column('comparison', 'created_user')
    op.drop_column('comparison', 'article_id_pair')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison', sa.Column('article_id_pair', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('comparison', sa.Column('created_user', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('comparison', 'pair_id')
    op.drop_column('comparison', 'article1')
    # ### end Alembic commands ###
