"""empty message

Revision ID: 8310b2025b13
Revises: 124fa42a7132
Create Date: 2017-04-18 20:14:46.998833

"""

# revision identifiers, used by Alembic.
revision = '8310b2025b13'
down_revision = '124fa42a7132'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison', sa.Column('created_user', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparison', 'created_user')
    # ### end Alembic commands ###
