"""empty message

Revision ID: d04a505491ec
Revises: 3a3656c5d37a
Create Date: 2017-04-17 22:07:53.663541

"""

# revision identifiers, used by Alembic.
revision = 'd04a505491ec'
down_revision = '3a3656c5d37a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revision', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revision', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
